apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app
    type: mvc
spec:
  containers:
    - name: app-mvc
      image: franklingonz02/clientewebazureadb2c:v1.0
      ports:
        - containerPort: 80